import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  'z64Sidebar': [
    {
      type: 'html',
      className: 'text--bold text--center',
      value: 'SoH/2Ship Modding',
    },
    { type: 'autogenerated', dirName: 'zship-modding' }, 
  ],
  '2ship2harkinianSidebar': [
    {
      type: 'html',
      className: 'text--bold text--center',
      value: '2 Ship 2 Harkinian',
    },
    { type: 'autogenerated', dirName: '2ship2harkinian' }, 
    {
      type: 'link',
      label: 'Github',
      href: 'https://github.com/HarbourMasters/2ship2harkinian/',
    },
    {
      type: 'link',
      label: 'Discord',
      href: 'https://discord.gg/shipofharkinian',
    },
    {
      type: 'link',
      label: 'Mod Library',
      href: 'https://gamebanana.com/games/20371',
    },
  ],
  'ship-of-harkinian': [
    {
      type: 'html',
      className: 'text--bold text--center',
      value: 'Ship of Harkinian',
    },
    { type: 'autogenerated', dirName: 'ship-of-harkinian' }, 
    {
      type: 'link',
      label: 'Github',
      href: 'https://github.com/HarbourMasters/Shipwright/',
    },
    {
      type: 'link',
      label: 'Discord',
      href: 'https://discord.gg/shipofharkinian',
    },
    {
      type: 'link',
      label: 'Mod Library',
      href: 'https://gamebanana.com/games/16121',
    },
  ],
};

export default sidebars;
